(function(){
var f=true,j=null,n=false,r,u=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";else if(b==
"function"&&typeof a.call=="undefined")return"object";return b}function v(a){return aa(a)=="array"}function w(a){var b=aa(a);return b=="array"||b=="object"&&typeof a.length=="number"}function x(a){return typeof a=="string"}Math.floor(Math.random()*2147483648).toString(36);function ba(a,b){function c(){}c.prototype=b.prototype;a.C=b.prototype;a.prototype=new c};function y(a){this.stack=Error().stack||"";if(a)this.message=String(a)}ba(y,Error);function ca(a){for(var b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,c)}return a}var da=/^[a-zA-Z0-9\-_.!~*'()]*$/;function z(a){a=String(a);if(!da.test(a))return encodeURIComponent(a);return a}function A(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};function ea(a,b){b.unshift(a);y.call(this,ca.apply(j,b));b.shift();this.B=a}ba(ea,y);function fa(a,b){if(!a){var c=Array.prototype.slice.call(arguments,2),d="Assertion failed";if(b){d+=": "+b;var e=c}throw new ea(""+d,e||[]);}return a};var B=Array.prototype,ga=B.indexOf?function(a,b,c){fa(a.length!=j);return B.indexOf.call(a,b,c)}:function(a,b,c){c=c==j?0:c<0?Math.max(0,a.length+c):c;if(x(a)){if(!x(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ha=B.forEach?function(a,b,c){fa(a.length!=j);B.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)};
function ia(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;if(v(c)||(d=w(c))&&c.hasOwnProperty("callee"))a.push.apply(a,c);else if(d)for(var e=a.length,g=c.length,i=0;i<g;i++)a[e+i]=c[i];else a.push(c)}};function ka(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function la(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};function ma(a){if(typeof a.i=="function")return a.i();if(x(a))return a.split("");if(w(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return ka(a)}function na(a,b,c){if(typeof a.forEach=="function")a.forEach(b,c);else if(w(a)||x(a))ha(a,b,c);else{var d;if(typeof a.p=="function")d=a.p();else if(typeof a.i!="function")if(w(a)||x(a)){d=[];for(var e=a.length,g=0;g<e;g++)d.push(g);d=d}else d=la(a);else d=void 0;e=ma(a);g=e.length;for(var i=0;i<g;i++)b.call(c,e[i],d&&d[i],a)}};function C(a){this.j={};this.c=[];var b=arguments.length;if(b>1){if(b%2)throw Error("Uneven number of arguments");for(var c=0;c<b;c+=2)this.n(arguments[c],arguments[c+1])}else if(a){if(a instanceof C){b=a.p();c=a.i()}else{b=la(a);c=ka(a)}for(var d=0;d<b.length;d++)this.n(b[d],c[d])}}r=C.prototype;r.b=0;r.z=0;r.i=function(){D(this);for(var a=[],b=0;b<this.c.length;b++)a.push(this.j[this.c[b]]);return a};r.p=function(){D(this);return this.c.concat()};r.d=function(a){return F(this.j,a)};
r.remove=function(a){if(F(this.j,a)){delete this.j[a];this.b--;this.z++;this.c.length>2*this.b&&D(this);return f}return n};function D(a){if(a.b!=a.c.length){for(var b=0,c=0;b<a.c.length;){var d=a.c[b];if(F(a.j,d))a.c[c++]=d;b++}a.c.length=c}if(a.b!=a.c.length){var e={};for(c=b=0;b<a.c.length;){d=a.c[b];if(!F(e,d)){a.c[c++]=d;e[d]=1}b++}a.c.length=c}}r.k=function(a,b){if(F(this.j,a))return this.j[a];return b};r.n=function(a,b){if(!F(this.j,a)){this.b++;this.c.push(a);this.z++}this.j[a]=b};r.t=function(){return new C(this)};
function F(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var oa=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function G(a,b){var c;if(a instanceof G){this.s(b==j?a.g:b);H(this,a.l);I(this,a.u);pa(this,a.o);qa(this,a.r);ra(this,a.q);J(this,a.e.t());K(this,a.m)}else if(a&&(c=String(a).match(oa))){this.s(!!b);H(this,c[1]||"",f);I(this,c[2]||"",f);pa(this,c[3]||"",f);qa(this,c[4]);ra(this,c[5]||"",f);J(this,c[6]||"",f);K(this,c[7]||"",f)}else{this.s(!!b);this.e=new L(j,this,this.g)}}r=G.prototype;r.l="";r.u="";r.o="";r.r=j;r.q="";r.m="";r.A=n;r.g=n;
r.toString=function(){if(this.f)return this.f;var a=[];this.l&&a.push(M(this.l,sa),":");if(this.o){a.push("//");this.u&&a.push(M(this.u,sa),"@");var b;b=this.o;b=x(b)?encodeURIComponent(b):j;a.push(b);this.r!=j&&a.push(":",String(this.r))}if(this.q){this.o&&this.q.charAt(0)!="/"&&a.push("/");a.push(M(this.q,ta))}(b=String(this.e))&&a.push("?",b);this.m&&a.push("#",M(this.m,ua));return this.f=a.join("")};
r.t=function(){var a=this.l,b=this.u,c=this.o,d=this.r,e=this.q,g=this.e.t(),i=this.m,l=new G(j,this.g);a&&H(l,a);b&&I(l,b);c&&pa(l,c);d&&qa(l,d);e&&ra(l,e);g&&J(l,g);i&&K(l,i);return l};function H(a,b,c){N(a);delete a.f;a.l=c?b?decodeURIComponent(b):"":b;if(a.l)a.l=a.l.replace(/:$/,"");return a}function I(a,b,c){N(a);delete a.f;a.u=c?b?decodeURIComponent(b):"":b;return a}function pa(a,b,c){N(a);delete a.f;a.o=c?b?decodeURIComponent(b):"":b;return a}
function qa(a,b){N(a);delete a.f;if(b){b=Number(b);if(isNaN(b)||b<0)throw Error("Bad port number "+b);a.r=b}else a.r=j;return a}function ra(a,b,c){N(a);delete a.f;a.q=c?b?decodeURIComponent(b):"":b;return a}function J(a,b,c){N(a);delete a.f;if(b instanceof L){a.e=b;a.e.w=a;a.e.s(a.g)}else{c||(b=M(b,va));a.e=new L(b,a,a.g)}return a}function K(a,b,c){N(a);delete a.f;a.m=c?b?decodeURIComponent(b):"":b;return a}function N(a){if(a.A)throw Error("Tried to modify a read-only Uri");}
r.s=function(a){this.g=a;this.e&&this.e.s(a)};var wa=/^[a-zA-Z0-9\-_.!~*'():\/;?]*$/;function M(a,b){var c=j;if(x(a)){c=a;wa.test(c)||(c=encodeURI(a));if(c.search(b)>=0)c=c.replace(b,xa)}return c}function xa(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var sa=/[#\/\?@]/g,ta=/[\#\?]/g,va=/[\#\?@]/g,ua=/#/g;function L(a,b,c){this.h=a||j;this.w=b||j;this.g=!!c}
function O(a){if(!a.a){a.a=new C;if(a.h)for(var b=a.h.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=j,g=j;if(d>=0){e=b[c].substring(0,d);g=b[c].substring(d+1)}else e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=P(a,e);a.add(e,g?decodeURIComponent(g.replace(/\+/g," ")):"")}}}r=L.prototype;r.a=j;r.b=j;r.add=function(a,b){O(this);Q(this);a=P(this,a);if(this.d(a)){var c=this.a.k(a);v(c)?c.push(b):this.a.n(a,[c,b])}else this.a.n(a,b);this.b++;return this};
r.remove=function(a){O(this);a=P(this,a);if(this.a.d(a)){Q(this);var b=this.a.k(a);if(v(b))this.b-=b.length;else this.b--;return this.a.remove(a)}return n};r.d=function(a){O(this);a=P(this,a);return this.a.d(a)};r.p=function(){O(this);for(var a=this.a.i(),b=this.a.p(),c=[],d=0;d<b.length;d++){var e=a[d];if(v(e))for(var g=0;g<e.length;g++)c.push(b[d]);else c.push(b[d])}return c};
r.i=function(a){O(this);if(a){a=P(this,a);if(this.d(a)){var b=this.a.k(a);if(v(b))return b;else{a=[];a.push(b)}}else a=[]}else{b=this.a.i();a=[];for(var c=0;c<b.length;c++){var d=b[c];v(d)?ia(a,d):a.push(d)}}return a};r.n=function(a,b){O(this);Q(this);a=P(this,a);if(this.d(a)){var c=this.a.k(a);if(v(c))this.b-=c.length;else this.b--}this.a.n(a,b);this.b++;return this};r.k=function(a,b){O(this);a=P(this,a);if(this.d(a)){var c=this.a.k(a);return v(c)?c[0]:c}else return b};
function za(a,b,c){O(a);Q(a);b=P(a,b);if(a.d(b)){var d=a.a.k(b);if(v(d))a.b-=d.length;else a.b--}if(c.length>0){a.a.n(b,c);a.b+=c.length}}r.toString=function(){if(this.h)return this.h;if(!this.a)return"";for(var a=[],b=0,c=this.a.p(),d=0;d<c.length;d++){var e=c[d],g=z(e);e=this.a.k(e);if(v(e))for(var i=0;i<e.length;i++){b>0&&a.push("&");a.push(g);e[i]!==""&&a.push("=",z(e[i]));b++}else{b>0&&a.push("&");a.push(g);e!==""&&a.push("=",z(e));b++}}return this.h=a.join("")};
function Q(a){delete a.v;delete a.h;a.w&&delete a.w.f}r.t=function(){var a=new L;if(this.v)a.v=this.v;if(this.h)a.h=this.h;if(this.a)a.a=this.a.t();return a};function P(a,b){var c=String(b);if(a.g)c=c.toLowerCase();return c}r.s=function(a){if(a&&!this.g){O(this);Q(this);na(this.a,function(b,c){var d=c.toLowerCase();if(c!=d){this.remove(c);this.add(d,b)}},this)}this.g=a};var R,Aa,S,Ba;function Ca(){return u.navigator?u.navigator.userAgent:j}Ba=S=Aa=R=n;var T;if(T=Ca()){var Da=u.navigator;R=T.indexOf("Opera")==0;Aa=!R&&T.indexOf("MSIE")!=-1;S=!R&&T.indexOf("WebKit")!=-1;Ba=!R&&!S&&Da.product=="Gecko"}var V=Aa,Ea=Ba,Fa=S,Ga;
a:{var W="",X;if(R&&u.opera){var Ha=u.opera.version;W=typeof Ha=="function"?Ha():Ha}else{if(Ea)X=/rv\:([^\);]+)(\)|;)/;else if(V)X=/MSIE\s+([^\);]+)(\)|;)/;else if(Fa)X=/WebKit\/(\S+)/;if(X){var Ia=X.exec(Ca());W=Ia?Ia[1]:""}}if(V){var Ja,Ka=u.document;Ja=Ka?Ka.documentMode:undefined;if(Ja>parseFloat(W)){Ga=String(Ja);break a}}Ga=W}var La={};
function Ma(a){var b;if(!(b=La[a])){b=0;for(var c=String(Ga).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),g=0;b==0&&g<e;g++){var i=c[g]||"",l=d[g]||"",o=RegExp("(\\d*)(\\D*)","g"),E=RegExp("(\\d*)(\\D*)","g");do{var k=o.exec(i)||["","",""],h=E.exec(l)||["","",""];if(k[0].length==0&&h[0].length==0)break;b=A(k[1].length==0?0:parseInt(k[1],10),h[1].length==0?0:parseInt(h[1],10))||A(k[2].length==0,h[2].length==
0)||A(k[2],h[2])}while(b==0)}b=La[a]=b>=0}return b};!V||Ma("9");V&&Ma("9");function Na(a,b,c){c=new G(c||window.location.href);b=b||n;for(var d in a)for(var e=a[d],g=0,i=e.length;g<i;g++){var l=e[g],o;o=l;var E=c.e,k=new L(c.m);if(o=E.d(o)?E.i(o):k.i(o)){l=l;o=o;E=b;k=d;var h=void 0;var m=document;h="a".toUpperCase();if(m.querySelectorAll&&m.querySelector&&(!Fa||document.compatMode=="CSS1Compat"||Ma("528"))&&(h||k))h=m.querySelectorAll(h+(k?"."+k:""));else if(k&&m.getElementsByClassName){m=m.getElementsByClassName(k);if(h){for(var s={},p=0,q=0,t=void 0;t=m[q];q++)if(h==
t.nodeName)s[p++]=t;s.length=p;h=s}else h=m}else{m=m.getElementsByTagName(h||"*");if(k){s={};for(q=p=0;t=m[q];q++){h=t.className;if(typeof h.split=="function"&&ga(h.split(/\s+/),k)>=0)s[p++]=t}s.length=p;h=s}else h=m}k=h;h=0;for(m=k.length;h<m;h++){p=s=new G(k[h].href);q=l;t=o;var ya=E,ja=p.e,Oa=p.m,U=j;if(ja.d(q)||!ya){za(ja,q,t);J(p,ja)}else{U=new L(Oa);if(U.d(q)||ya){za(U,q,t);K(p,U.toString())}}k[h].href=s.toString()}}}}var Y="gweb.uri.updateLinks".split("."),Z=u;
!(Y[0]in Z)&&Z.execScript&&Z.execScript("var "+Y[0]);for(var $;Y.length&&($=Y.shift());)if(!Y.length&&Na!==undefined)Z[$]=Na;else Z=Z[$]?Z[$]:Z[$]={};
})()